name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Arch Linux
      uses: uD83D/setup-arch@v1

    - name: Install dependencies
      run: |
        pacman -Sy --noconfirm jdk17-openjdk unzip git

    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Upload PlayIntegrityFix.zip
      uses: actions/upload-artifact@v4
      with:
        name: PlayIntegrityFix
        path: module/*